version: '3'

services:
  nextjs:
    build:
      context: ./nextjs-school
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - ./nextjs-school/.env.local

  graphql:
    build:
      context: ./School/School
      dockerfile: Dockerfile
    expose: 
      - "80"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    expose: 
      - "80"
    env_file:
      - ./auth/.env

  caddy:
    image: caddy:2.1.1
    container_name: caddy
    restart: always
    volumes:
      - caddy-stuff:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=true

volumes:
  caddy-stuff: